_target_: src.models.deepcycle_module.DeepCycleModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

net:
  _target_: src.models.components.mlp.MLP
  dim: 2 # equal to dim of genes
  time_varying: true

geodesic_net:
  _target_: src.models.components.mlp.MLP
  dim: 4 # equal to dim of genes * 2
  out_dim: 2 # equal to dim of genes
  time_varying: true

# compile model for faster training with pytorch 2.0
compile: false

sigma: 0.01
alpha: 0.1